from stay_in_the_ring.stay_in_the_ring import StayInTheRing
from blackcat import BlackCat
from spingame import SpinGame
from mirrors.minigame import MirrorsMinigame
from shoot_targets.shoot_targets import ShootTargets
from leprechaunBeatemUp.leprechaunBeatemUp import LeprechaunBeatemUp
from cutlery_fall.cutlery_fall import CutleryFall
from its_raining_beer.its_raining_beer import ItsRainingBeer
from crackgame import CrackGame
from chiotteclean import ChiotteGame
from ultimate_pong.ultimate_pong import UltimatePong
from ladders import LaddersMinigame
from lockpick.game import Lockpick
from kamehameha.minigame import KamehamehaMinigame
from rope.rope import Rope
from treeballz import TreeBallz
from asteroid_showdown import AsteroidShowdown
