from blackcat import BlackCat
from spingame import SpinGame
from mirrors.minigame import MirrorsMinigame
from shoot_targets.shoot_targets import ShootTargets
from leprechaunBeatemUp.leprechaunBeatemUp import LeprechaunBeatemUp
from cutlery_fall.cutlery_fall import CutleryFall
from its_raining_beer.its_raining_beer import ItsRainingBeer
from crackgame import CrackGame
from chiotteclean import ChiotteGame
